keeping up with changes (#340)
* removed a strange bug we noticed

* refactor: removed AlternativeMods folder

* Add local image option

embed for thumbnail and image

* Update set time restriction mod

1. Allow user use variable as cooldown time
2. User now can switch with time measurement includes (ms, s, m, h)

* Update changelog

* Delete Age_Calculator_MOD.js

* Delete TEMPLATE.js

get outa here! stop coming back!

* Resolve issue #288 Message Embed Object (#292)

* Fix issue #288 Message Embed Object

* Remove if statement

* Update README.md

* Update README.md

* fix(AwaitResponse): made it compatible with events

* added set time restriction feature (#294)

* Fix issue #288 Message Embed Object

* Remove if statement

* Added feature restrict by server or global

* feat(RunScript): added changes made by MrGold (#295)

* Create run_script.js

* fix(GameServer): amount of players (#297)

* Update game_server_MOD.js

* Update game_server_MOD.js

* Update actions/game_server_MOD.js

Co-authored-by: Almeida <42935195+Almeeida@users.noreply.github.com>

* fix(Store Server Info) (#300)

* Fix issue #288 Message Embed Object

* Remove if statement

* Added feature restrict by server or global

* Fix some error

TypeError: Cannot read property 'size' of undefined

* Update Slice_MOD.js (#305)

Parse Int of data.storage to fix undefined bug

* Command Description + Get Command Description (#301)

* Command Description mods.

Added two mods:
Command Description
Get Command Description
- - -
Command Description is an action that holds a description for a command. This is used along with Get Command Description to make it easier to make help/info commands.

* Update description_MOD.js

* Added blank init function

* Added version 2 of send json to webapi

now supports; put, post, patch, delete, it can also now take headers, and basic authentication parameters

* Update send_json_to_webapi_MOD.js

It seems last time i updated parse from stored json with itself, now the correct change was made?

* Update send_message_to_console_MOD.js (#321)

Added color support through [chalk](https://www.npmjs.com/package/chalk) (Auto-install through WrexMODS). Also added an Error Message (Non-Fatal) to Empty Logs both in DBM and in Logs. And a GUI change which displays the log color as it would be in the command prompt.

* Update store_member_info.js (#313)

* Update store_member_info.js

Added two new options:

- Member Join Timestamp
- Member Account Creation Timestamp

* Create set_slowmode_MOD.js

* Update edit_message.js (#318)

Beta Branch PR of https://github.com/dbm-network/mods/pull/316

* Update store_server_info.js (#320)

Adds server boost count and server premium tier

* Added Insert at Position to File Control (#322)

* Added Insert at Position to File Control

New option added called "Insert" which appends at a given line.

* Update file_control_MOD.js

* remove stupid extra whitespace

Co-authored-by: General Wrex <1731139+generalwrex@users.noreply.github.com>

* Update file_control_MOD.js

Better Version Cross-Compatibility. Basically Switched the HTML and Case values for "Delete" to not be randomly overwritten by "Insert" on mod install.

* Update file_control_MOD.js

Patched hidden attribute to be distributed at the correct selection indexes. My bad for not having done this earlier.

* run SQL Query wont force unneeded npm modules now

* fixed operatorAliases warning

* Update file_control_MOD.js

Fixed Field display displaying wrong fields at wrong times.

* Update file_control_MOD.js

ooga booga did some funny shit

* Update send_message_to_console_MOD.js (#330)

Added backwards compatibility as I ran into the issue a few times. Only works in the bot, DBM will still show the action missing.

* moved Run SQL Query to the right place

* Removed bengis (#333)

* Update Play Youtube (#331)

* Update Play Youtube

Check if msg exists to avoid `TypeError: Cannot read property 'author' of undefined` when used in an event

* Update play_youtube.js

* Create google_image_search_MOD.js (#334)

* Create google_image_search_MOD.js

* Update google_image_search_MOD.js

* Update README.md

Co-authored-by: Detroit Whiskey <45453611+DetroitWhiskey136@users.noreply.github.com>
Co-authored-by: LeonZ <leon_yy99@hotmail.com>
Co-authored-by: TheMonDon <bforster48@gmail.com>
Co-authored-by: General Wrex <1731139+generalwrex@users.noreply.github.com>
Co-authored-by: ForceBlood <33997884+ForceBlood@users.noreply.github.com>
Co-authored-by: Mndlsscrg <39963404+Mndlsscrg@users.noreply.github.com>
Co-authored-by: hazelpy <59073660+hazelpy@users.noreply.github.com>
Co-authored-by: RigidStudios <34319439+RigidStudios@users.noreply.github.com>
Co-authored-by: Jasper Lutz Severino <jasperworld9@gmail.com>
Co-authored-by: Mindlesscargo <39963404+Mindlesscargo@users.noreply.github.com>
Co-authored-by: Matthew <matheus_fabris@hotmail.com>